name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: push
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "The job was automatically triggered by a ${{ github.event_name }}"
            - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
            - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}"
            - name: Checkout Repository Code
              uses: actions/checkout@v4
            - run: echo "The ${{ github.repository }} has been cloned to the runner"
            - run: echo "The workflow is ready to test our code on the runner"
            - name: List files in the repository
              run: |
                ls ${{ github.workspace }}
            - run: echo "The job status is ${{ job.status }}"
